### ISSUE TITLE
panic after installation 

### ISSUE THREAD

**Issue by xoac** [codesections/mnemonic#18]
I just installed mn and do
```
mn list 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and back-trace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
stack backtrace:
   0:     0x55fb7133a423 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h00d1e05a61bd440b
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55fb71334cc8 - std::sys_common::backtrace::_print::hc0d53aca8da62f75
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x55fb71339472 - std::panicking::default_hook::{{closure}}::h46d30bcc4bfff149
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:211
   3:     0x55fb713391dd - std::panicking::default_hook::h017696c2a8b7b16f
                               at src/libstd/panicking.rs:227
   4:     0x55fb71339b20 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                               at src/libstd/panicking.rs:491
   5:     0x55fb713396a1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                               at src/libstd/panicking.rs:398
   6:     0x55fb71339585 - rust_begin_unwind
                               at src/libstd/panicking.rs:325
   7:     0x55fb71352a3c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                               at src/libcore/panicking.rs:95
   8:     0x55fb711053b9 - core::result::unwrap_failed::h6e467703d0e0a567
   9:     0x55fb710fea3b - mn::state::State::from_config_file::h611230c844c1bf53
  10:     0x55fb71104186 - mn::main::hc8aea7800c70629f
  11:     0x55fb71103572 - std::rt::lang_start::{{closure}}::h22125b5942599dfd
  12:     0x55fb71339522 - std::panicking::try::do_call::h69790245ac2d03fe
                               at src/libstd/rt.rs:59
                               at src/libstd/panicking.rs:310
  13:     0x55fb7134c0c9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:102
  14:     0x55fb71339ef3 - std::rt::lang_start_internal::h540c897fe52ba9c5
                               at src/libstd/panicking.rs:289
                               at src/libstd/panic.rs:398
                               at src/libstd/rt.rs:58
  15:     0x55fb711046e1 - main
  16:     0x7ff8d9772222 - __libc_start_main
  17:     0x55fb710ce1cd - _start
  18:                0x0 - <unknown>
```

I think it's due to some configuration file that is missing?

**Comment by codesections** [comment]
Thanks very much for raising this.  I'll take a look!

**Comment by codesections** [comment]
This should be fixed by #19.  Do you mind letting me know if that resolves the issue?

(The bug was that `mn` was creating the _file_ but not the directory, and the tests only tested for the absence of the file, not the absence of the directory.)

**Comment by xoac** [comment]
```
mn list                                                                                                                                                       
You don't have any mnemonics yet.  Use `mn add <MNEMONIC>` to create your first mnemonic.
```

**Comment by codesections** [comment]
Thanks very much for the prompt follow-up and the through bug report—if everyone acted like that, open-source software would be in vastly better shape.

Very much appreciated!
